### ISSUE TITLE
POST Data Reading Issue

### ISSUE THREAD

**Issue by wanxu** [iancaffey/http#1] opened 2017-06-30 09:07 UTC
I tried to use this project in my own project ,but i found that i couldn't get data by post request.

**Comment by iancaffey** [comment] 2017-06-30 21:37
It's not actively developed but it fully supports the HTTP 1.0 protocol. 

I just noticed a bug with readBody and fixed it in the latest commit https://github.com/iancaffey/http/commit/c1c20361faa1c3f99ac124aee2cc91ccd149f95f. 

An unfortunate consequence is now the body is exposed as a `BufferedReader` instead of a `Channel` due to the buffering of the input causing issues with reading the body (some of the body would be buffered within the reader). 

The following handler successfully read in POST data.

```java
@Post("/")
public HttpHandler index() {
    return (reader, writer) -> {
        Map<String, String[]> headers = reader.readHeaders();
        BufferedReader body = reader.readBody();
        int bodyLength = Integer.parseInt(headers.get("Content-Length")[0]);
        ByteArrayOutputStream out = new ByteArrayOutputStream(bodyLength);
        for (int i = 0; i < bodyLength; i++)
            out.write(body.read());
        System.out.println("Body: " + out.toString());
    };
}
```

Tested using `curl --data "param1=value1&param2=value2" 127.0.0.1:8080`.

**Comment by iancaffey** [comment] 2017-06-30 21:43
The HttpHandler API doesn't provide any advanced parsing of the body of an HTTP POST, like decoding the key/value pairs. 

If you'd like to contribute to the project, such an addition would be extremely valuable, so feel free to propose a solution you find intuitive and effective.

HttpHandler is a low level interface for dealing with raw data, only offering the appropriate methods to step through the HTTP protocol when it comes over the wire.

Support for a wrapper on top of HttpHandler which parses form data and allows serializing Java data types internally would be a nice addition. 

`Router#accept` would need to be adjusted to support more than HttpHandler.

**Comment by iancaffey** [comment] 2017-07-01 03:45
If you encounter any more issues or wish to make any changes, feel free to open more issues. I'll close this since I confirmed the POST reading was fixed.

**Closed by iancaffey** 2017-07-01 03:45 UTC

**Comment by wanxu** [comment] 2017-07-01 17:30
Thank you for your attention and fix, I`ll try to contribute some code to this project aiming at advanced parsing of the body.
